// Code generated by protoc-gen-go. DO NOT EDIT.
// source: units/extensions.proto

package units

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

var E_DefaultDegrees = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*Degrees)(nil),
	Field:         60002,
	Name:          "units.default_degrees",
	Tag:           "bytes,60002,opt,name=default_degrees",
	Filename:      "units/extensions.proto",
}

var E_MinDegrees = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*Degrees)(nil),
	Field:         60003,
	Name:          "units.min_degrees",
	Tag:           "bytes,60003,opt,name=min_degrees",
	Filename:      "units/extensions.proto",
}

var E_MaxDegrees = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*Degrees)(nil),
	Field:         60004,
	Name:          "units.max_degrees",
	Tag:           "bytes,60004,opt,name=max_degrees",
	Filename:      "units/extensions.proto",
}

var E_DefaultMeters = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*Meters)(nil),
	Field:         60005,
	Name:          "units.default_meters",
	Tag:           "bytes,60005,opt,name=default_meters",
	Filename:      "units/extensions.proto",
}

var E_MinMeters = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*Meters)(nil),
	Field:         60006,
	Name:          "units.min_meters",
	Tag:           "bytes,60006,opt,name=min_meters",
	Filename:      "units/extensions.proto",
}

var E_MaxMeters = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*Meters)(nil),
	Field:         60007,
	Name:          "units.max_meters",
	Tag:           "bytes,60007,opt,name=max_meters",
	Filename:      "units/extensions.proto",
}

var E_DefaultMetersPerSecond = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*MetersPerSecond)(nil),
	Field:         60008,
	Name:          "units.default_meters_per_second",
	Tag:           "bytes,60008,opt,name=default_meters_per_second",
	Filename:      "units/extensions.proto",
}

var E_MinMetersPerSecond = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*MetersPerSecond)(nil),
	Field:         60009,
	Name:          "units.min_meters_per_second",
	Tag:           "bytes,60009,opt,name=min_meters_per_second",
	Filename:      "units/extensions.proto",
}

var E_MaxMetersPerSecond = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*MetersPerSecond)(nil),
	Field:         60010,
	Name:          "units.max_meters_per_second",
	Tag:           "bytes,60010,opt,name=max_meters_per_second",
	Filename:      "units/extensions.proto",
}

var E_DefaultPascals = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*Pascal)(nil),
	Field:         60011,
	Name:          "units.default_pascals",
	Tag:           "bytes,60011,opt,name=default_pascals",
	Filename:      "units/extensions.proto",
}

var E_MinPascals = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*Pascal)(nil),
	Field:         60012,
	Name:          "units.min_pascals",
	Tag:           "bytes,60012,opt,name=min_pascals",
	Filename:      "units/extensions.proto",
}

var E_MaxPascals = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*Pascal)(nil),
	Field:         60013,
	Name:          "units.max_pascals",
	Tag:           "bytes,60013,opt,name=max_pascals",
	Filename:      "units/extensions.proto",
}

var E_DefaultCelsius = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*Celsius)(nil),
	Field:         60014,
	Name:          "units.default_celsius",
	Tag:           "bytes,60014,opt,name=default_celsius",
	Filename:      "units/extensions.proto",
}

var E_MinCelsius = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*Celsius)(nil),
	Field:         60015,
	Name:          "units.min_celsius",
	Tag:           "bytes,60015,opt,name=min_celsius",
	Filename:      "units/extensions.proto",
}

var E_MaxCelsius = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*Celsius)(nil),
	Field:         60016,
	Name:          "units.max_celsius",
	Tag:           "bytes,60016,opt,name=max_celsius",
	Filename:      "units/extensions.proto",
}

var E_DefaultMetersPerSecondSquared = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*MetersPerSecondSquared)(nil),
	Field:         60020,
	Name:          "units.default_meters_per_second_squared",
	Tag:           "bytes,60020,opt,name=default_meters_per_second_squared",
	Filename:      "units/extensions.proto",
}

var E_MinMetersPerSecondSquared = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*MetersPerSecondSquared)(nil),
	Field:         60021,
	Name:          "units.min_meters_per_second_squared",
	Tag:           "bytes,60021,opt,name=min_meters_per_second_squared",
	Filename:      "units/extensions.proto",
}

var E_MaxMetersPerSecondSquared = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*MetersPerSecondSquared)(nil),
	Field:         60022,
	Name:          "units.max_meters_per_second_squared",
	Tag:           "bytes,60022,opt,name=max_meters_per_second_squared",
	Filename:      "units/extensions.proto",
}

func init() {
	proto.RegisterExtension(E_DefaultDegrees)
	proto.RegisterExtension(E_MinDegrees)
	proto.RegisterExtension(E_MaxDegrees)
	proto.RegisterExtension(E_DefaultMeters)
	proto.RegisterExtension(E_MinMeters)
	proto.RegisterExtension(E_MaxMeters)
	proto.RegisterExtension(E_DefaultMetersPerSecond)
	proto.RegisterExtension(E_MinMetersPerSecond)
	proto.RegisterExtension(E_MaxMetersPerSecond)
	proto.RegisterExtension(E_DefaultPascals)
	proto.RegisterExtension(E_MinPascals)
	proto.RegisterExtension(E_MaxPascals)
	proto.RegisterExtension(E_DefaultCelsius)
	proto.RegisterExtension(E_MinCelsius)
	proto.RegisterExtension(E_MaxCelsius)
	proto.RegisterExtension(E_DefaultMetersPerSecondSquared)
	proto.RegisterExtension(E_MinMetersPerSecondSquared)
	proto.RegisterExtension(E_MaxMetersPerSecondSquared)
}

func init() { proto.RegisterFile("units/extensions.proto", fileDescriptor_d9098ea9a3573ef1) }

var fileDescriptor_d9098ea9a3573ef1 = []byte{
	// 488 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0xd5, 0x4d, 0x8b, 0xd4, 0x30,
	0x18, 0x07, 0x70, 0x06, 0x51, 0x30, 0xcb, 0xae, 0x38, 0xe0, 0xe0, 0x2e, 0x14, 0xd6, 0x9b, 0x22,
	0xb4, 0xa0, 0xb7, 0x1e, 0x55, 0xbc, 0x0d, 0x33, 0x74, 0x10, 0xc5, 0x4b, 0xc9, 0xb4, 0xcf, 0xd4,
	0x48, 0x9b, 0xd4, 0x24, 0x85, 0x1c, 0x3d, 0xfa, 0x01, 0xfd, 0x04, 0xbe, 0xbf, 0xeb, 0x41, 0x3d,
	0x2f, 0x6d, 0xd2, 0x4e, 0x3b, 0xd3, 0xd2, 0xcc, 0x65, 0x21, 0xe9, 0xe6, 0xf7, 0x3c, 0x49, 0xf3,
	0xef, 0xa0, 0x59, 0x41, 0x89, 0x14, 0x1e, 0x28, 0x09, 0x54, 0x10, 0x46, 0x85, 0x9b, 0x73, 0x26,
	0xd9, 0xf4, 0x72, 0x35, 0x7f, 0x76, 0x9e, 0x30, 0x96, 0xa4, 0xe0, 0x55, 0x93, 0xeb, 0x62, 0xe3,
	0xc5, 0x20, 0x22, 0x4e, 0x72, 0xc9, 0xb8, 0xfe, 0xc7, 0xb3, 0xeb, 0x1a, 0xa8, 0xfe, 0xea, 0x29,
	0xff, 0x19, 0xba, 0x16, 0xc3, 0x06, 0x17, 0xa9, 0x0c, 0x63, 0x48, 0x38, 0x80, 0x98, 0x3a, 0xae,
	0x86, 0xdc, 0x1a, 0x72, 0x1f, 0x13, 0x48, 0xe3, 0x45, 0x2e, 0xcb, 0x9a, 0x37, 0xdf, 0xbd, 0xbd,
	0x74, 0x3e, 0xb9, 0x7d, 0x74, 0xef, 0xc4, 0xd5, 0xce, 0x23, 0xbd, 0x2c, 0x38, 0x31, 0x8e, 0x19,
	0xfb, 0x4b, 0x74, 0x94, 0x11, 0x6a, 0xab, 0xbe, 0x1f, 0x50, 0x51, 0x46, 0x68, 0x5b, 0xc4, 0xca,
	0x56, 0xfc, 0x30, 0x28, 0x62, 0x55, 0x8b, 0x4f, 0x50, 0xdd, 0x75, 0x98, 0x81, 0x04, 0x3e, 0x8a,
	0x7e, 0x34, 0xe8, 0xb1, 0x41, 0xe7, 0xd5, 0xaa, 0xe0, 0xd8, 0x28, 0x7a, 0xe8, 0xcf, 0x51, 0xd9,
	0xb6, 0x25, 0xf9, 0xa9, 0x9f, 0xbc, 0x9a, 0x11, 0xda, 0xe2, 0xb0, 0xb2, 0xe4, 0x3e, 0x0f, 0x71,
	0x58, 0x19, 0x8e, 0xa3, 0xd3, 0xee, 0xa6, 0xc3, 0x1c, 0x78, 0x28, 0x20, 0x62, 0x34, 0x1e, 0xd3,
	0xbf, 0x18, 0x7d, 0xd6, 0xd1, 0x97, 0xc0, 0x57, 0xd5, 0xf2, 0x60, 0xd6, 0x39, 0x88, 0x66, 0xde,
	0x7f, 0x89, 0x6e, 0x6c, 0x4f, 0xe4, 0x80, 0x7a, 0x5f, 0x47, 0xea, 0x4d, 0x9b, 0x53, 0xea, 0xd6,
	0x6a, 0x8e, 0xeb, 0x80, 0x5a, 0xdf, 0x46, 0x6b, 0xd5, 0x47, 0xb8, 0xad, 0xf5, 0x74, 0x1b, 0x9f,
	0x1c, 0x8b, 0x08, 0xa7, 0xa3, 0xef, 0xe7, 0xfb, 0xce, 0xfb, 0x59, 0x56, 0xcb, 0x9a, 0xf4, 0xe8,
	0xa1, 0xf0, 0x17, 0x3a, 0x3d, 0x96, 0xe8, 0x8f, 0x7e, 0xb4, 0xbc, 0x85, 0x6d, 0x10, 0x2b, 0x5b,
	0xf0, 0xe7, 0x10, 0x88, 0x55, 0x0d, 0xb6, 0xbe, 0x1c, 0x11, 0xa4, 0x82, 0x14, 0xa3, 0xe8, 0xaf,
	0x9d, 0x44, 0x3e, 0xd4, 0xcb, 0x9a, 0xbd, 0x9b, 0x71, 0xfd, 0xe5, 0xb0, 0x54, 0x7f, 0x0f, 0xa8,
	0xe5, 0xe6, 0xdb, 0x22, 0x56, 0xb6, 0xe2, 0x9f, 0x41, 0x11, 0xab, 0x5a, 0x7c, 0x33, 0x41, 0xb7,
	0x06, 0x53, 0x14, 0x8a, 0x57, 0x05, 0xe6, 0x30, 0x7a, 0xe3, 0xfe, 0x9a, 0x42, 0x4e, 0xff, 0x8d,
	0x5b, 0x69, 0x25, 0x70, 0xfa, 0x43, 0x65, 0x1e, 0xfb, 0xaf, 0x27, 0xc8, 0xe9, 0x0d, 0x97, 0x6d,
	0x1b, 0xff, 0xec, 0xda, 0x38, 0xdd, 0xcf, 0x5a, 0xa7, 0x85, 0xbe, 0xcc, 0xd9, 0xb6, 0xf0, 0xdf,
	0xb6, 0x85, 0xbd, 0x08, 0x9a, 0x47, 0x0f, 0xee, 0x3e, 0xbf, 0x93, 0x10, 0xf9, 0xa2, 0x58, 0xbb,
	0x11, 0xcb, 0x3c, 0x4c, 0x78, 0x86, 0x73, 0x8f, 0x50, 0x09, 0x7c, 0x83, 0x23, 0x10, 0x9e, 0xe0,
	0x91, 0x97, 0x30, 0xfd, 0xdb, 0xb7, 0xbe, 0x52, 0x75, 0x71, 0xff, 0x22, 0x00, 0x00, 0xff, 0xff,
	0xc5, 0xbe, 0x34, 0xf4, 0x52, 0x07, 0x00, 0x00,
}
