// Code generated by protoc-gen-go. DO NOT EDIT.
// source: units/extensions.proto

package units

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

var E_DefaultDegrees = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*Degrees)(nil),
	Field:         60002,
	Name:          "units.default_degrees",
	Tag:           "bytes,60002,opt,name=default_degrees",
	Filename:      "units/extensions.proto",
}

var E_MinDegrees = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*Degrees)(nil),
	Field:         60003,
	Name:          "units.min_degrees",
	Tag:           "bytes,60003,opt,name=min_degrees",
	Filename:      "units/extensions.proto",
}

var E_MaxDegrees = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*Degrees)(nil),
	Field:         60004,
	Name:          "units.max_degrees",
	Tag:           "bytes,60004,opt,name=max_degrees",
	Filename:      "units/extensions.proto",
}

var E_DefaultMeters = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*Meters)(nil),
	Field:         60005,
	Name:          "units.default_meters",
	Tag:           "bytes,60005,opt,name=default_meters",
	Filename:      "units/extensions.proto",
}

var E_MinMeters = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*Meters)(nil),
	Field:         60006,
	Name:          "units.min_meters",
	Tag:           "bytes,60006,opt,name=min_meters",
	Filename:      "units/extensions.proto",
}

var E_MaxMeters = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*Meters)(nil),
	Field:         60007,
	Name:          "units.max_meters",
	Tag:           "bytes,60007,opt,name=max_meters",
	Filename:      "units/extensions.proto",
}

var E_DefaultMetersPerSecond = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*MetersPerSecond)(nil),
	Field:         60008,
	Name:          "units.default_meters_per_second",
	Tag:           "bytes,60008,opt,name=default_meters_per_second",
	Filename:      "units/extensions.proto",
}

var E_MinMetersPerSecond = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*MetersPerSecond)(nil),
	Field:         60009,
	Name:          "units.min_meters_per_second",
	Tag:           "bytes,60009,opt,name=min_meters_per_second",
	Filename:      "units/extensions.proto",
}

var E_MaxMetersPerSecond = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*MetersPerSecond)(nil),
	Field:         60010,
	Name:          "units.max_meters_per_second",
	Tag:           "bytes,60010,opt,name=max_meters_per_second",
	Filename:      "units/extensions.proto",
}

var E_DefaultPascals = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*Pascals)(nil),
	Field:         60011,
	Name:          "units.default_pascals",
	Tag:           "bytes,60011,opt,name=default_pascals",
	Filename:      "units/extensions.proto",
}

var E_MinPascals = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*Pascals)(nil),
	Field:         60012,
	Name:          "units.min_pascals",
	Tag:           "bytes,60012,opt,name=min_pascals",
	Filename:      "units/extensions.proto",
}

var E_MaxPascals = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*Pascals)(nil),
	Field:         60013,
	Name:          "units.max_pascals",
	Tag:           "bytes,60013,opt,name=max_pascals",
	Filename:      "units/extensions.proto",
}

var E_DefaultCelsius = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*Celsius)(nil),
	Field:         60014,
	Name:          "units.default_celsius",
	Tag:           "bytes,60014,opt,name=default_celsius",
	Filename:      "units/extensions.proto",
}

var E_MinCelsius = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*Celsius)(nil),
	Field:         60015,
	Name:          "units.min_celsius",
	Tag:           "bytes,60015,opt,name=min_celsius",
	Filename:      "units/extensions.proto",
}

var E_MaxCelsius = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*Celsius)(nil),
	Field:         60016,
	Name:          "units.max_celsius",
	Tag:           "bytes,60016,opt,name=max_celsius",
	Filename:      "units/extensions.proto",
}

var E_DefaultMetersPerSecondSquared = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*MetersPerSecondSquared)(nil),
	Field:         60020,
	Name:          "units.default_meters_per_second_squared",
	Tag:           "bytes,60020,opt,name=default_meters_per_second_squared",
	Filename:      "units/extensions.proto",
}

var E_MinMetersPerSecondSquared = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*MetersPerSecondSquared)(nil),
	Field:         60021,
	Name:          "units.min_meters_per_second_squared",
	Tag:           "bytes,60021,opt,name=min_meters_per_second_squared",
	Filename:      "units/extensions.proto",
}

var E_MaxMetersPerSecondSquared = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*MetersPerSecondSquared)(nil),
	Field:         60022,
	Name:          "units.max_meters_per_second_squared",
	Tag:           "bytes,60022,opt,name=max_meters_per_second_squared",
	Filename:      "units/extensions.proto",
}

func init() {
	proto.RegisterExtension(E_DefaultDegrees)
	proto.RegisterExtension(E_MinDegrees)
	proto.RegisterExtension(E_MaxDegrees)
	proto.RegisterExtension(E_DefaultMeters)
	proto.RegisterExtension(E_MinMeters)
	proto.RegisterExtension(E_MaxMeters)
	proto.RegisterExtension(E_DefaultMetersPerSecond)
	proto.RegisterExtension(E_MinMetersPerSecond)
	proto.RegisterExtension(E_MaxMetersPerSecond)
	proto.RegisterExtension(E_DefaultPascals)
	proto.RegisterExtension(E_MinPascals)
	proto.RegisterExtension(E_MaxPascals)
	proto.RegisterExtension(E_DefaultCelsius)
	proto.RegisterExtension(E_MinCelsius)
	proto.RegisterExtension(E_MaxCelsius)
	proto.RegisterExtension(E_DefaultMetersPerSecondSquared)
	proto.RegisterExtension(E_MinMetersPerSecondSquared)
	proto.RegisterExtension(E_MaxMetersPerSecondSquared)
}

func init() { proto.RegisterFile("units/extensions.proto", fileDescriptor_d9098ea9a3573ef1) }

var fileDescriptor_d9098ea9a3573ef1 = []byte{
	// 482 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0xd5, 0xcb, 0x8b, 0xd4, 0x30,
	0x18, 0x00, 0x70, 0x06, 0x51, 0x30, 0xcb, 0xae, 0x38, 0xe0, 0xe0, 0x2e, 0x14, 0xd6, 0x9b, 0x22,
	0xb4, 0xa0, 0xb7, 0x1e, 0x55, 0xbc, 0x2d, 0x0e, 0x5d, 0x04, 0xf1, 0x52, 0x32, 0xed, 0x37, 0x35,
	0xd2, 0x26, 0x35, 0x49, 0x21, 0x47, 0x8f, 0xfe, 0x81, 0xfe, 0x05, 0xbe, 0xdf, 0x7a, 0x50, 0xcf,
	0x4b, 0x9b, 0xa4, 0xdb, 0xee, 0x36, 0x34, 0x7b, 0x19, 0x48, 0x32, 0xf9, 0x7d, 0x8f, 0xc9, 0xc7,
	0xa0, 0x55, 0x43, 0x89, 0x14, 0x11, 0x28, 0x09, 0x54, 0x10, 0x46, 0x45, 0x58, 0x73, 0x26, 0xd9,
	0xf2, 0x72, 0xb7, 0x7f, 0x70, 0x58, 0x30, 0x56, 0x94, 0x10, 0x75, 0x9b, 0x9b, 0x66, 0x1b, 0xe5,
	0x20, 0x32, 0x4e, 0x6a, 0xc9, 0xb8, 0xfe, 0xe2, 0xc1, 0x75, 0x0d, 0x74, 0x9f, 0x7a, 0x2b, 0x7e,
	0x86, 0xae, 0xe5, 0xb0, 0xc5, 0x4d, 0x29, 0xd3, 0x1c, 0x0a, 0x0e, 0x20, 0x96, 0x41, 0xa8, 0xa1,
	0xd0, 0x42, 0xe1, 0x63, 0x02, 0x65, 0xfe, 0xa4, 0x96, 0x6d, 0xcc, 0x9b, 0xef, 0xde, 0x5e, 0x3a,
	0x5c, 0xdc, 0xde, 0xb9, 0xb7, 0x17, 0x6a, 0xe7, 0x91, 0xbe, 0x96, 0xec, 0x19, 0xc7, 0xac, 0xe3,
	0x35, 0xda, 0xa9, 0x08, 0xf5, 0x55, 0xdf, 0x3b, 0x54, 0x54, 0x11, 0x3a, 0x14, 0xb1, 0xf2, 0x15,
	0x3f, 0x38, 0x45, 0xac, 0xac, 0xf8, 0x14, 0xd9, 0xac, 0xd3, 0x0a, 0x24, 0xf0, 0x59, 0xf4, 0xa3,
	0x41, 0x77, 0x0d, 0x7a, 0xd4, 0xdd, 0x4a, 0x76, 0x8d, 0xa2, 0x97, 0xf1, 0x11, 0x6a, 0xd3, 0xf6,
	0x24, 0x3f, 0x4d, 0x93, 0x57, 0x2b, 0x42, 0x07, 0x1c, 0x56, 0x9e, 0xdc, 0x67, 0x17, 0x87, 0x95,
	0xe1, 0x38, 0xda, 0x1f, 0x17, 0x9d, 0xd6, 0xc0, 0x53, 0x01, 0x19, 0xa3, 0xf9, 0x9c, 0xfe, 0xc5,
	0xe8, 0xab, 0x91, 0xbe, 0x06, 0x7e, 0xdc, 0x5d, 0x4f, 0x56, 0xa3, 0x46, 0xf4, 0xfb, 0xf1, 0x4b,
	0x74, 0xe3, 0xb4, 0x23, 0x17, 0x88, 0xf7, 0x75, 0x26, 0xde, 0xb2, 0xef, 0xd2, 0x38, 0x56, 0xdf,
	0xae, 0x0b, 0xc4, 0xfa, 0x36, 0x1b, 0xcb, 0xb6, 0xf0, 0x34, 0xd6, 0x60, 0x7c, 0x6a, 0x2c, 0x32,
	0x5c, 0xce, 0xfe, 0x3e, 0xdf, 0xcf, 0x3c, 0xcb, 0xb5, 0xbe, 0xd6, 0x8f, 0x8f, 0x59, 0xdb, 0xf1,
	0xf1, 0x54, 0x7f, 0x38, 0xd4, 0xf6, 0x1d, 0x0e, 0x45, 0xac, 0x7c, 0xc5, 0x9f, 0x4e, 0x11, 0x2b,
	0x2b, 0x0e, 0xaa, 0xcf, 0xa0, 0x14, 0xa4, 0x99, 0x55, 0x7f, 0x9d, 0x51, 0x1f, 0xea, 0x6b, 0x7d,
	0xf5, 0x66, 0x6d, 0xab, 0xf7, 0x54, 0x7f, 0x3b, 0xd4, 0xb6, 0xfa, 0xa1, 0x88, 0x95, 0xaf, 0xf8,
	0xc7, 0x29, 0x62, 0x65, 0xc5, 0x37, 0x0b, 0x74, 0xcb, 0x39, 0x48, 0xa9, 0x78, 0xd5, 0x60, 0x0e,
	0xb3, 0x8f, 0xee, 0xaf, 0x09, 0x14, 0x4c, 0x3f, 0xba, 0x63, 0xad, 0x24, 0xc1, 0xf4, 0x5c, 0x99,
	0xe3, 0xf8, 0xf5, 0x02, 0x05, 0x93, 0xf3, 0xe5, 0x9b, 0xc6, 0x3f, 0xbf, 0x34, 0xf6, 0xcf, 0x8f,
	0xdb, 0x28, 0x85, 0xa9, 0xb1, 0xf3, 0x4d, 0xe1, 0xbf, 0x6f, 0x0a, 0xe7, 0xa6, 0xd0, 0x1c, 0x3d,
	0xb8, 0xfb, 0xfc, 0x4e, 0x41, 0xe4, 0x8b, 0x66, 0x13, 0x66, 0xac, 0x8a, 0x30, 0xe1, 0x15, 0xae,
	0x23, 0x42, 0x25, 0xf0, 0x2d, 0xce, 0x40, 0x44, 0x82, 0x67, 0x51, 0xc1, 0xf4, 0xdf, 0xdf, 0xe6,
	0x4a, 0x97, 0xc5, 0xfd, 0x93, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe8, 0xe0, 0xc5, 0x07, 0x55, 0x07,
	0x00, 0x00,
}
