// Code generated by protoc-gen-go. DO NOT EDIT.
// source: telemetry/report.proto

package telemetry

import (
	fmt "fmt"
	_ "github.com/airmap/interfaces/src/go"
	measurements "github.com/airmap/interfaces/src/go/measurements"
	tracking "github.com/airmap/interfaces/src/go/tracking"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Report models a measurement at a given point in time.
type Report struct {
	Observed   *timestamp.Timestamp `protobuf:"bytes,1,opt,name=observed,proto3" json:"observed,omitempty"`
	Identities []*tracking.Identity `protobuf:"bytes,2,rep,name=identities,proto3" json:"identities,omitempty"`
	// details is a discriminated union of all measurement types.
	//
	// Types that are valid to be assigned to Details:
	//	*Report_Spatial_
	//	*Report_Atmospheric_
	//	*Report_System_
	Details              isReport_Details `protobuf_oneof:"details"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Report) Reset()         { *m = Report{} }
func (m *Report) String() string { return proto.CompactTextString(m) }
func (*Report) ProtoMessage()    {}
func (*Report) Descriptor() ([]byte, []int) {
	return fileDescriptor_822b117a32fda6fc, []int{0}
}

func (m *Report) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Report.Unmarshal(m, b)
}
func (m *Report) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Report.Marshal(b, m, deterministic)
}
func (m *Report) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Report.Merge(m, src)
}
func (m *Report) XXX_Size() int {
	return xxx_messageInfo_Report.Size(m)
}
func (m *Report) XXX_DiscardUnknown() {
	xxx_messageInfo_Report.DiscardUnknown(m)
}

var xxx_messageInfo_Report proto.InternalMessageInfo

func (m *Report) GetObserved() *timestamp.Timestamp {
	if m != nil {
		return m.Observed
	}
	return nil
}

func (m *Report) GetIdentities() []*tracking.Identity {
	if m != nil {
		return m.Identities
	}
	return nil
}

type isReport_Details interface {
	isReport_Details()
}

type Report_Spatial_ struct {
	Spatial *Report_Spatial `protobuf:"bytes,3,opt,name=spatial,proto3,oneof"`
}

type Report_Atmospheric_ struct {
	Atmospheric *Report_Atmospheric `protobuf:"bytes,4,opt,name=atmospheric,proto3,oneof"`
}

type Report_System_ struct {
	System *Report_System `protobuf:"bytes,5,opt,name=system,proto3,oneof"`
}

func (*Report_Spatial_) isReport_Details() {}

func (*Report_Atmospheric_) isReport_Details() {}

func (*Report_System_) isReport_Details() {}

func (m *Report) GetDetails() isReport_Details {
	if m != nil {
		return m.Details
	}
	return nil
}

func (m *Report) GetSpatial() *Report_Spatial {
	if x, ok := m.GetDetails().(*Report_Spatial_); ok {
		return x.Spatial
	}
	return nil
}

func (m *Report) GetAtmospheric() *Report_Atmospheric {
	if x, ok := m.GetDetails().(*Report_Atmospheric_); ok {
		return x.Atmospheric
	}
	return nil
}

func (m *Report) GetSystem() *Report_System {
	if x, ok := m.GetDetails().(*Report_System_); ok {
		return x.System
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Report) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Report_Spatial_)(nil),
		(*Report_Atmospheric_)(nil),
		(*Report_System_)(nil),
	}
}

// Spatial bundles geospatial measurements.
type Report_Spatial struct {
	Position             *measurements.Position     `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	Velocity             *measurements.Velocity     `protobuf:"bytes,2,opt,name=velocity,proto3" json:"velocity,omitempty"`
	Orientation          *measurements.Orientation  `protobuf:"bytes,3,opt,name=orientation,proto3" json:"orientation,omitempty"`
	Acceleration         *measurements.Acceleration `protobuf:"bytes,4,opt,name=acceleration,proto3" json:"acceleration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *Report_Spatial) Reset()         { *m = Report_Spatial{} }
func (m *Report_Spatial) String() string { return proto.CompactTextString(m) }
func (*Report_Spatial) ProtoMessage()    {}
func (*Report_Spatial) Descriptor() ([]byte, []int) {
	return fileDescriptor_822b117a32fda6fc, []int{0, 0}
}

func (m *Report_Spatial) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Report_Spatial.Unmarshal(m, b)
}
func (m *Report_Spatial) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Report_Spatial.Marshal(b, m, deterministic)
}
func (m *Report_Spatial) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Report_Spatial.Merge(m, src)
}
func (m *Report_Spatial) XXX_Size() int {
	return xxx_messageInfo_Report_Spatial.Size(m)
}
func (m *Report_Spatial) XXX_DiscardUnknown() {
	xxx_messageInfo_Report_Spatial.DiscardUnknown(m)
}

var xxx_messageInfo_Report_Spatial proto.InternalMessageInfo

func (m *Report_Spatial) GetPosition() *measurements.Position {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *Report_Spatial) GetVelocity() *measurements.Velocity {
	if m != nil {
		return m.Velocity
	}
	return nil
}

func (m *Report_Spatial) GetOrientation() *measurements.Orientation {
	if m != nil {
		return m.Orientation
	}
	return nil
}

func (m *Report_Spatial) GetAcceleration() *measurements.Acceleration {
	if m != nil {
		return m.Acceleration
	}
	return nil
}

// Atmospheric bundles atmospheric measurements at a given position.
type Report_Atmospheric struct {
	Position             *measurements.Position    `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	Pressure             *measurements.Pressure    `protobuf:"bytes,2,opt,name=pressure,proto3" json:"pressure,omitempty"`
	Temperature          *measurements.Temperature `protobuf:"bytes,3,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Wind                 *measurements.Wind        `protobuf:"bytes,4,opt,name=wind,proto3" json:"wind,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *Report_Atmospheric) Reset()         { *m = Report_Atmospheric{} }
func (m *Report_Atmospheric) String() string { return proto.CompactTextString(m) }
func (*Report_Atmospheric) ProtoMessage()    {}
func (*Report_Atmospheric) Descriptor() ([]byte, []int) {
	return fileDescriptor_822b117a32fda6fc, []int{0, 1}
}

func (m *Report_Atmospheric) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Report_Atmospheric.Unmarshal(m, b)
}
func (m *Report_Atmospheric) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Report_Atmospheric.Marshal(b, m, deterministic)
}
func (m *Report_Atmospheric) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Report_Atmospheric.Merge(m, src)
}
func (m *Report_Atmospheric) XXX_Size() int {
	return xxx_messageInfo_Report_Atmospheric.Size(m)
}
func (m *Report_Atmospheric) XXX_DiscardUnknown() {
	xxx_messageInfo_Report_Atmospheric.DiscardUnknown(m)
}

var xxx_messageInfo_Report_Atmospheric proto.InternalMessageInfo

func (m *Report_Atmospheric) GetPosition() *measurements.Position {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *Report_Atmospheric) GetPressure() *measurements.Pressure {
	if m != nil {
		return m.Pressure
	}
	return nil
}

func (m *Report_Atmospheric) GetTemperature() *measurements.Temperature {
	if m != nil {
		return m.Temperature
	}
	return nil
}

func (m *Report_Atmospheric) GetWind() *measurements.Wind {
	if m != nil {
		return m.Wind
	}
	return nil
}

type Report_System struct {
	Endurance            *duration.Duration         `protobuf:"bytes,1,opt,name=endurance,proto3" json:"endurance,omitempty"`
	Subsystems           []*Report_System_Subsystem `protobuf:"bytes,2,rep,name=subsystems,proto3" json:"subsystems,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *Report_System) Reset()         { *m = Report_System{} }
func (m *Report_System) String() string { return proto.CompactTextString(m) }
func (*Report_System) ProtoMessage()    {}
func (*Report_System) Descriptor() ([]byte, []int) {
	return fileDescriptor_822b117a32fda6fc, []int{0, 2}
}

func (m *Report_System) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Report_System.Unmarshal(m, b)
}
func (m *Report_System) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Report_System.Marshal(b, m, deterministic)
}
func (m *Report_System) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Report_System.Merge(m, src)
}
func (m *Report_System) XXX_Size() int {
	return xxx_messageInfo_Report_System.Size(m)
}
func (m *Report_System) XXX_DiscardUnknown() {
	xxx_messageInfo_Report_System.DiscardUnknown(m)
}

var xxx_messageInfo_Report_System proto.InternalMessageInfo

func (m *Report_System) GetEndurance() *duration.Duration {
	if m != nil {
		return m.Endurance
	}
	return nil
}

func (m *Report_System) GetSubsystems() []*Report_System_Subsystem {
	if m != nil {
		return m.Subsystems
	}
	return nil
}

type Report_System_Subsystem struct {
	// Types that are valid to be assigned to Details:
	//	*Report_System_Subsystem_Battery
	Details              isReport_System_Subsystem_Details `protobuf_oneof:"details"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *Report_System_Subsystem) Reset()         { *m = Report_System_Subsystem{} }
func (m *Report_System_Subsystem) String() string { return proto.CompactTextString(m) }
func (*Report_System_Subsystem) ProtoMessage()    {}
func (*Report_System_Subsystem) Descriptor() ([]byte, []int) {
	return fileDescriptor_822b117a32fda6fc, []int{0, 2, 0}
}

func (m *Report_System_Subsystem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Report_System_Subsystem.Unmarshal(m, b)
}
func (m *Report_System_Subsystem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Report_System_Subsystem.Marshal(b, m, deterministic)
}
func (m *Report_System_Subsystem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Report_System_Subsystem.Merge(m, src)
}
func (m *Report_System_Subsystem) XXX_Size() int {
	return xxx_messageInfo_Report_System_Subsystem.Size(m)
}
func (m *Report_System_Subsystem) XXX_DiscardUnknown() {
	xxx_messageInfo_Report_System_Subsystem.DiscardUnknown(m)
}

var xxx_messageInfo_Report_System_Subsystem proto.InternalMessageInfo

type isReport_System_Subsystem_Details interface {
	isReport_System_Subsystem_Details()
}

type Report_System_Subsystem_Battery struct {
	Battery *Report_System_Battery `protobuf:"bytes,1,opt,name=battery,proto3,oneof"`
}

func (*Report_System_Subsystem_Battery) isReport_System_Subsystem_Details() {}

func (m *Report_System_Subsystem) GetDetails() isReport_System_Subsystem_Details {
	if m != nil {
		return m.Details
	}
	return nil
}

func (m *Report_System_Subsystem) GetBattery() *Report_System_Battery {
	if x, ok := m.GetDetails().(*Report_System_Subsystem_Battery); ok {
		return x.Battery
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Report_System_Subsystem) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Report_System_Subsystem_Battery)(nil),
	}
}

type Report_System_Battery struct {
	Id                   string                    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Voltage              float64                   `protobuf:"fixed64,2,opt,name=voltage,proto3" json:"voltage,omitempty"`
	Temperature          *measurements.Temperature `protobuf:"bytes,3,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Capacity             float64                   `protobuf:"fixed64,4,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Charge               float64                   `protobuf:"fixed64,5,opt,name=charge,proto3" json:"charge,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *Report_System_Battery) Reset()         { *m = Report_System_Battery{} }
func (m *Report_System_Battery) String() string { return proto.CompactTextString(m) }
func (*Report_System_Battery) ProtoMessage()    {}
func (*Report_System_Battery) Descriptor() ([]byte, []int) {
	return fileDescriptor_822b117a32fda6fc, []int{0, 2, 1}
}

func (m *Report_System_Battery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Report_System_Battery.Unmarshal(m, b)
}
func (m *Report_System_Battery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Report_System_Battery.Marshal(b, m, deterministic)
}
func (m *Report_System_Battery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Report_System_Battery.Merge(m, src)
}
func (m *Report_System_Battery) XXX_Size() int {
	return xxx_messageInfo_Report_System_Battery.Size(m)
}
func (m *Report_System_Battery) XXX_DiscardUnknown() {
	xxx_messageInfo_Report_System_Battery.DiscardUnknown(m)
}

var xxx_messageInfo_Report_System_Battery proto.InternalMessageInfo

func (m *Report_System_Battery) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Report_System_Battery) GetVoltage() float64 {
	if m != nil {
		return m.Voltage
	}
	return 0
}

func (m *Report_System_Battery) GetTemperature() *measurements.Temperature {
	if m != nil {
		return m.Temperature
	}
	return nil
}

func (m *Report_System_Battery) GetCapacity() float64 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func (m *Report_System_Battery) GetCharge() float64 {
	if m != nil {
		return m.Charge
	}
	return 0
}

func init() {
	proto.RegisterType((*Report)(nil), "telemetry.Report")
	proto.RegisterType((*Report_Spatial)(nil), "telemetry.Report.Spatial")
	proto.RegisterType((*Report_Atmospheric)(nil), "telemetry.Report.Atmospheric")
	proto.RegisterType((*Report_System)(nil), "telemetry.Report.System")
	proto.RegisterType((*Report_System_Subsystem)(nil), "telemetry.Report.System.Subsystem")
	proto.RegisterType((*Report_System_Battery)(nil), "telemetry.Report.System.Battery")
}

func init() { proto.RegisterFile("telemetry/report.proto", fileDescriptor_822b117a32fda6fc) }

var fileDescriptor_822b117a32fda6fc = []byte{
	// 610 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0xeb, 0x34, 0xe4, 0xcf, 0x04, 0x21, 0xb4, 0x87, 0xe2, 0x5a, 0x2a, 0xad, 0x7a, 0x40,
	0xbd, 0x60, 0x4b, 0x41, 0xfc, 0x91, 0xe0, 0x92, 0xa8, 0x87, 0x72, 0xa2, 0xda, 0x56, 0x20, 0x71,
	0xdb, 0xd8, 0x53, 0x77, 0x85, 0xed, 0xb5, 0x76, 0x27, 0x85, 0xdc, 0x2a, 0x1e, 0x81, 0x67, 0x40,
	0x3c, 0x14, 0x4f, 0x83, 0xbc, 0x5e, 0x3b, 0x0e, 0x4d, 0x0f, 0x88, 0xe3, 0x7a, 0x7e, 0xdf, 0xec,
	0xe7, 0x6f, 0x76, 0x60, 0x8f, 0x30, 0xc3, 0x1c, 0x49, 0xaf, 0x22, 0x8d, 0xa5, 0xd2, 0x14, 0x96,
	0x5a, 0x91, 0x62, 0xe3, 0xf6, 0x7b, 0x70, 0x98, 0x2a, 0x95, 0x66, 0x18, 0xd9, 0xc2, 0x62, 0x79,
	0x15, 0x91, 0xcc, 0xd1, 0x90, 0xc8, 0xcb, 0x9a, 0x0d, 0x9e, 0xfe, 0x0d, 0x24, 0x4b, 0x2d, 0x48,
	0xaa, 0xc2, 0xd5, 0x1f, 0xe3, 0x37, 0xc2, 0xc2, 0x48, 0x55, 0x18, 0xf7, 0xe5, 0x30, 0x47, 0x61,
	0x96, 0x1a, 0x73, 0x2c, 0xc8, 0x44, 0xdd, 0x83, 0x03, 0x9e, 0x90, 0x16, 0xf1, 0x17, 0x59, 0xa4,
	0x91, 0x4c, 0xb0, 0x20, 0x49, 0xab, 0xba, 0x70, 0xfc, 0x63, 0x0c, 0x03, 0x6e, 0x8d, 0xb2, 0x57,
	0x30, 0x52, 0x0b, 0x83, 0xfa, 0x06, 0x13, 0xdf, 0x3b, 0xf2, 0x4e, 0x26, 0xd3, 0x20, 0xac, 0x9d,
	0x84, 0x8d, 0x93, 0xf0, 0xb2, 0xb1, 0xca, 0x5b, 0x96, 0x4d, 0x01, 0x5c, 0x53, 0x89, 0xc6, 0xef,
	0x1d, 0xed, 0x9e, 0x4c, 0xa6, 0x2c, 0x6c, 0x2e, 0x0c, 0xdf, 0xbb, 0x0b, 0x79, 0x87, 0x62, 0x2f,
	0x61, 0x68, 0x4a, 0x41, 0x52, 0x64, 0xfe, 0xae, 0xbd, 0x6a, 0x3f, 0x6c, 0x03, 0x0a, 0x6b, 0x3f,
	0xe1, 0x45, 0x0d, 0x9c, 0xed, 0xf0, 0x86, 0x65, 0x33, 0x98, 0x08, 0xca, 0x95, 0x29, 0xaf, 0x51,
	0xcb, 0xd8, 0xef, 0x5b, 0xe9, 0xc1, 0x5d, 0xe9, 0x6c, 0x0d, 0x9d, 0xed, 0xf0, 0xae, 0x86, 0x4d,
	0x61, 0x60, 0x56, 0x86, 0x30, 0xf7, 0x1f, 0x58, 0xb5, 0xbf, 0xe5, 0x62, 0x5b, 0x3f, 0xdb, 0xe1,
	0x8e, 0x0c, 0x6e, 0x7b, 0x30, 0x74, 0x6e, 0xd8, 0x14, 0x46, 0xa5, 0x32, 0xb2, 0x1a, 0x87, 0x4b,
	0x69, 0x2f, 0xdc, 0x08, 0xfc, 0xdc, 0x55, 0x79, 0xcb, 0xb1, 0x37, 0x30, 0xba, 0xc1, 0x4c, 0xc5,
	0x92, 0x56, 0x7e, 0x6f, 0x9b, 0xe6, 0xa3, 0xab, 0xce, 0xfb, 0xb7, 0xbf, 0x0e, 0x3c, 0xde, 0xd2,
	0xd5, 0x0f, 0x2b, 0x2d, 0xb1, 0x20, 0x3b, 0xff, 0x36, 0xab, 0x0d, 0xf1, 0x87, 0x35, 0xe0, 0xf4,
	0x5d, 0x0d, 0x3b, 0x85, 0x87, 0x22, 0x8e, 0x31, 0xc3, 0xfa, 0x0d, 0xb9, 0xd0, 0x82, 0xcd, 0x1e,
	0xb3, 0x0e, 0xe1, 0x9a, 0x6c, 0xa8, 0x82, 0xdf, 0x1e, 0x4c, 0x66, 0x1b, 0x31, 0xfe, 0x7b, 0x0c,
	0x95, 0x46, 0xa3, 0xa9, 0x98, 0xed, 0x31, 0x9c, 0xbb, 0x2a, 0x6f, 0x39, 0xf6, 0x16, 0x26, 0x84,
	0x79, 0x59, 0xd9, 0xa8, 0x64, 0x5b, 0x03, 0xb8, 0x5c, 0x03, 0xbc, 0x4b, 0xb3, 0x67, 0xd0, 0xff,
	0x2a, 0x8b, 0xc4, 0xfd, 0x32, 0xdb, 0x54, 0x7d, 0x92, 0x45, 0xc2, 0x6d, 0x3d, 0xf8, 0xbe, 0x0b,
	0x83, 0x7a, 0xe8, 0xec, 0x35, 0x8c, 0xb1, 0xa8, 0xf6, 0xad, 0x88, 0xd1, 0xfd, 0xd8, 0xfe, 0x9d,
	0x2d, 0x38, 0x75, 0xfb, 0xc8, 0xd7, 0x2c, 0x9b, 0x03, 0x98, 0xe5, 0xa2, 0x7e, 0x30, 0xcd, 0x16,
	0x1c, 0xdf, 0xf7, 0xb6, 0xc2, 0x8b, 0x06, 0xe5, 0x1d, 0x55, 0x70, 0x09, 0xe3, 0xb6, 0xc0, 0xde,
	0xc1, 0x70, 0x21, 0x88, 0x50, 0xaf, 0x9c, 0x8f, 0xa3, 0x7b, 0xbb, 0xcd, 0x6b, 0xae, 0xda, 0x14,
	0x27, 0x99, 0x8f, 0x61, 0x98, 0x20, 0x09, 0x99, 0x99, 0xe0, 0xa7, 0x07, 0x43, 0x47, 0xb0, 0x47,
	0xd0, 0x93, 0xf5, 0x76, 0x8f, 0x79, 0x4f, 0x26, 0xcc, 0x87, 0xe1, 0x8d, 0xca, 0x48, 0xa4, 0xf5,
	0x44, 0x3c, 0xde, 0x1c, 0xff, 0x2f, 0xf8, 0x00, 0x46, 0xb1, 0x28, 0x85, 0x7d, 0xf0, 0x7d, 0xdb,
	0xb7, 0x3d, 0xb3, 0x3d, 0x18, 0xc4, 0xd7, 0x42, 0xa7, 0x68, 0x17, 0xd0, 0xe3, 0xee, 0xd4, 0x71,
	0x3c, 0x8f, 0x3e, 0x3f, 0x4f, 0x25, 0x5d, 0x2f, 0x17, 0x61, 0xac, 0xf2, 0x48, 0x48, 0x9d, 0x8b,
	0x32, 0x92, 0x05, 0xa1, 0xbe, 0x12, 0x31, 0x9a, 0xc8, 0xe8, 0x38, 0x4a, 0x55, 0xd4, 0xc6, 0xb1,
	0x18, 0xd8, 0xd1, 0xbc, 0xf8, 0x13, 0x00, 0x00, 0xff, 0xff, 0xc0, 0xb1, 0xdf, 0x0a, 0x7e, 0x05,
	0x00, 0x00,
}
