// Code generated by protoc-gen-go. DO NOT EDIT.
// source: telemetry/report.proto

package telemetry

import (
	fmt "fmt"
	_ "github.com/airmap/interfaces/src/go"
	measurements "github.com/airmap/interfaces/src/go/measurements"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Report models a measurement at a given point in time.
type Report struct {
	Observed *timestamp.Timestamp `protobuf:"bytes,1,opt,name=observed,proto3" json:"observed,omitempty"`
	// details is a discriminated union of all measurement types.
	//
	// Types that are valid to be assigned to Details:
	//	*Report_Spatial_
	//	*Report_Atmospheric_
	Details              isReport_Details `protobuf_oneof:"details"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Report) Reset()         { *m = Report{} }
func (m *Report) String() string { return proto.CompactTextString(m) }
func (*Report) ProtoMessage()    {}
func (*Report) Descriptor() ([]byte, []int) {
	return fileDescriptor_822b117a32fda6fc, []int{0}
}

func (m *Report) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Report.Unmarshal(m, b)
}
func (m *Report) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Report.Marshal(b, m, deterministic)
}
func (m *Report) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Report.Merge(m, src)
}
func (m *Report) XXX_Size() int {
	return xxx_messageInfo_Report.Size(m)
}
func (m *Report) XXX_DiscardUnknown() {
	xxx_messageInfo_Report.DiscardUnknown(m)
}

var xxx_messageInfo_Report proto.InternalMessageInfo

func (m *Report) GetObserved() *timestamp.Timestamp {
	if m != nil {
		return m.Observed
	}
	return nil
}

type isReport_Details interface {
	isReport_Details()
}

type Report_Spatial_ struct {
	Spatial *Report_Spatial `protobuf:"bytes,2,opt,name=spatial,proto3,oneof"`
}

type Report_Atmospheric_ struct {
	Atmospheric *Report_Atmospheric `protobuf:"bytes,3,opt,name=atmospheric,proto3,oneof"`
}

func (*Report_Spatial_) isReport_Details() {}

func (*Report_Atmospheric_) isReport_Details() {}

func (m *Report) GetDetails() isReport_Details {
	if m != nil {
		return m.Details
	}
	return nil
}

func (m *Report) GetSpatial() *Report_Spatial {
	if x, ok := m.GetDetails().(*Report_Spatial_); ok {
		return x.Spatial
	}
	return nil
}

func (m *Report) GetAtmospheric() *Report_Atmospheric {
	if x, ok := m.GetDetails().(*Report_Atmospheric_); ok {
		return x.Atmospheric
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Report) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Report_Spatial_)(nil),
		(*Report_Atmospheric_)(nil),
	}
}

// Spatial bundles geospatial measurements.
type Report_Spatial struct {
	Position             *measurements.Position    `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	Velocity             *measurements.Velocity    `protobuf:"bytes,2,opt,name=velocity,proto3" json:"velocity,omitempty"`
	Orientation          *measurements.Orientation `protobuf:"bytes,3,opt,name=orientation,proto3" json:"orientation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *Report_Spatial) Reset()         { *m = Report_Spatial{} }
func (m *Report_Spatial) String() string { return proto.CompactTextString(m) }
func (*Report_Spatial) ProtoMessage()    {}
func (*Report_Spatial) Descriptor() ([]byte, []int) {
	return fileDescriptor_822b117a32fda6fc, []int{0, 0}
}

func (m *Report_Spatial) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Report_Spatial.Unmarshal(m, b)
}
func (m *Report_Spatial) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Report_Spatial.Marshal(b, m, deterministic)
}
func (m *Report_Spatial) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Report_Spatial.Merge(m, src)
}
func (m *Report_Spatial) XXX_Size() int {
	return xxx_messageInfo_Report_Spatial.Size(m)
}
func (m *Report_Spatial) XXX_DiscardUnknown() {
	xxx_messageInfo_Report_Spatial.DiscardUnknown(m)
}

var xxx_messageInfo_Report_Spatial proto.InternalMessageInfo

func (m *Report_Spatial) GetPosition() *measurements.Position {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *Report_Spatial) GetVelocity() *measurements.Velocity {
	if m != nil {
		return m.Velocity
	}
	return nil
}

func (m *Report_Spatial) GetOrientation() *measurements.Orientation {
	if m != nil {
		return m.Orientation
	}
	return nil
}

// Atmospheric bundles atmospheric measurements at a given position.
type Report_Atmospheric struct {
	Position             *measurements.Position    `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	Pressure             *measurements.Pressure    `protobuf:"bytes,2,opt,name=pressure,proto3" json:"pressure,omitempty"`
	Temperature          *measurements.Temperature `protobuf:"bytes,3,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Wind                 *measurements.Wind        `protobuf:"bytes,4,opt,name=wind,proto3" json:"wind,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *Report_Atmospheric) Reset()         { *m = Report_Atmospheric{} }
func (m *Report_Atmospheric) String() string { return proto.CompactTextString(m) }
func (*Report_Atmospheric) ProtoMessage()    {}
func (*Report_Atmospheric) Descriptor() ([]byte, []int) {
	return fileDescriptor_822b117a32fda6fc, []int{0, 1}
}

func (m *Report_Atmospheric) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Report_Atmospheric.Unmarshal(m, b)
}
func (m *Report_Atmospheric) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Report_Atmospheric.Marshal(b, m, deterministic)
}
func (m *Report_Atmospheric) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Report_Atmospheric.Merge(m, src)
}
func (m *Report_Atmospheric) XXX_Size() int {
	return xxx_messageInfo_Report_Atmospheric.Size(m)
}
func (m *Report_Atmospheric) XXX_DiscardUnknown() {
	xxx_messageInfo_Report_Atmospheric.DiscardUnknown(m)
}

var xxx_messageInfo_Report_Atmospheric proto.InternalMessageInfo

func (m *Report_Atmospheric) GetPosition() *measurements.Position {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *Report_Atmospheric) GetPressure() *measurements.Pressure {
	if m != nil {
		return m.Pressure
	}
	return nil
}

func (m *Report_Atmospheric) GetTemperature() *measurements.Temperature {
	if m != nil {
		return m.Temperature
	}
	return nil
}

func (m *Report_Atmospheric) GetWind() *measurements.Wind {
	if m != nil {
		return m.Wind
	}
	return nil
}

func init() {
	proto.RegisterType((*Report)(nil), "telemetry.Report")
	proto.RegisterType((*Report_Spatial)(nil), "telemetry.Report.Spatial")
	proto.RegisterType((*Report_Atmospheric)(nil), "telemetry.Report.Atmospheric")
}

func init() { proto.RegisterFile("telemetry/report.proto", fileDescriptor_822b117a32fda6fc) }

var fileDescriptor_822b117a32fda6fc = []byte{
	// 392 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0x3f, 0x6f, 0xd4, 0x30,
	0x18, 0xc6, 0x1b, 0x1a, 0xf5, 0xae, 0xce, 0x82, 0x3c, 0x54, 0x21, 0x12, 0x2a, 0x62, 0x40, 0x2c,
	0xd8, 0x52, 0x11, 0x08, 0x89, 0xa9, 0x37, 0x75, 0xa3, 0x32, 0x15, 0x48, 0x6c, 0x4e, 0xf2, 0x36,
	0xb5, 0x14, 0xff, 0x91, 0xfd, 0xde, 0xc1, 0x6d, 0x7c, 0x29, 0x16, 0x3e, 0x0a, 0x0b, 0x5f, 0x05,
	0xc5, 0xf1, 0xe5, 0x72, 0x70, 0x13, 0x63, 0xfc, 0xfe, 0x7e, 0x7e, 0x9f, 0x47, 0x31, 0xb9, 0x40,
	0xe8, 0x41, 0x03, 0xfa, 0x2d, 0xf7, 0xe0, 0xac, 0x47, 0xe6, 0xbc, 0x45, 0x4b, 0xcf, 0xa7, 0xf3,
	0xea, 0xb2, 0xb3, 0xb6, 0xeb, 0x81, 0xc7, 0x41, 0xbd, 0xbe, 0xe7, 0xa8, 0x34, 0x04, 0x94, 0xda,
	0x8d, 0x6c, 0xf5, 0x18, 0xbe, 0x21, 0x98, 0xa0, 0xac, 0x09, 0xe9, 0xe4, 0x52, 0x83, 0x0c, 0x6b,
	0x0f, 0x1a, 0x0c, 0x06, 0x3e, 0xff, 0x18, 0x81, 0xe7, 0xbf, 0x73, 0x72, 0x26, 0xe2, 0x3e, 0xfa,
	0x96, 0x2c, 0x6d, 0x1d, 0xc0, 0x6f, 0xa0, 0x2d, 0xb3, 0x67, 0xd9, 0xcb, 0xe2, 0xaa, 0x62, 0xe3,
	0x46, 0xb6, 0xdb, 0xc8, 0xee, 0x76, 0x1b, 0xc5, 0xc4, 0xd2, 0x37, 0x64, 0x11, 0x9c, 0x44, 0x25,
	0xfb, 0xf2, 0x51, 0xd4, 0x9e, 0xb0, 0x29, 0x33, 0x1b, 0xef, 0x66, 0x1f, 0x47, 0xe0, 0xe6, 0x44,
	0xec, 0x58, 0x7a, 0x4d, 0x0a, 0x89, 0xda, 0x06, 0xf7, 0x00, 0x5e, 0x35, 0xe5, 0x69, 0x54, 0x9f,
	0xfe, 0xab, 0x5e, 0xef, 0xa1, 0x9b, 0x13, 0x31, 0x77, 0xaa, 0x9f, 0x19, 0x59, 0xa4, 0x9b, 0xe9,
	0x15, 0x59, 0x3a, 0x1b, 0x14, 0x2a, 0x6b, 0x52, 0xfa, 0x0b, 0x76, 0xd0, 0xf7, 0x36, 0x4d, 0xc5,
	0xc4, 0xd1, 0x77, 0x64, 0xb9, 0x81, 0xde, 0x36, 0x0a, 0xb7, 0x29, 0xfa, 0x5f, 0xce, 0xa7, 0x34,
	0x5d, 0xe5, 0xdf, 0x7f, 0x94, 0x99, 0x98, 0xe8, 0x21, 0xbc, 0xf5, 0x0a, 0x0c, 0xca, 0xb8, 0xf0,
	0x34, 0xf5, 0x3e, 0x90, 0x3f, 0xec, 0x81, 0xe4, 0xcf, 0x9d, 0xea, 0x57, 0x46, 0x8a, 0x59, 0xb7,
	0xff, 0x2a, 0x30, 0x38, 0x1e, 0xc2, 0xc0, 0x1c, 0x2f, 0x70, 0x9b, 0xa6, 0x62, 0xe2, 0xe8, 0x7b,
	0x52, 0x20, 0x68, 0x07, 0x5e, 0xe2, 0xa0, 0x1d, 0x8d, 0x7e, 0xb7, 0x07, 0xc4, 0x9c, 0xa6, 0x2f,
	0x48, 0xfe, 0x55, 0x99, 0xb6, 0xcc, 0xa3, 0x45, 0x0f, 0xad, 0xcf, 0xca, 0xb4, 0x22, 0xce, 0x57,
	0xe7, 0x64, 0xd1, 0x02, 0x4a, 0xd5, 0x87, 0x15, 0xff, 0xf2, 0xaa, 0x53, 0xf8, 0xb0, 0xae, 0x59,
	0x63, 0x35, 0x97, 0xca, 0x6b, 0xe9, 0xb8, 0x32, 0x08, 0xfe, 0x5e, 0x36, 0x10, 0x78, 0xf0, 0x0d,
	0xef, 0x2c, 0x9f, 0xfe, 0x7b, 0x7d, 0x16, 0x5f, 0xdb, 0xeb, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x87, 0xa2, 0x41, 0x8d, 0x12, 0x03, 0x00, 0x00,
}
